### ISSUE TITLE
Check if a player is online

### ISSUE THREAD

**Issue by Auties00** [Xilixir/FortniteAPI#10]
Once I get all of my online friends I'm unable to check if they are online. Can you please add this feature?

**Comment by julian-exile** [comment]
No, there's no point

**Comment by Auties00** [comment]
Yes it's super usefull. I tried to implement that by myself but I failed

**Comment by Auties00** [comment]
Thanks for the help!

**Comment by Auties00** [comment]
You can also say "I'm unable to do it"

**Comment by julian-exile** [comment]
I'm not unable to do it; It's a waste of time and I'm busy.

**Comment by Auties00** [comment]
I don't want it now, I asked if you can add it when you can
