### ISSUE TITLE
question to api

### ISSUE THREAD

**Issue by fiftyy** [Xilixir/FortniteAPI#3]
Does the player must have a epicgames account?

**Comment by julian-exile** [comment]
yes this is for pc

**Comment by prezt0** [comment]
Would it be possible to write something similar what agora.gg has done? Basically it allows the web app (in this case agora.gg) permission to access data from the user's Epic Games account.

First you click sign in.
<img width="1440" alt="screen shot 2018-03-25 at 11 59 11 pm" src="https://user-images.githubusercontent.com/31043772/37886620-6ab4747c-308a-11e8-8124-1bd80116e30a.png">

Then it redirects you to **accounts.epicgames.com/authorize/ {then a code here}** and asks you to sign in using your epic games login.
<img width="1440" alt="screen shot 2018-03-26 at 12 09 51 am" src="https://user-images.githubusercontent.com/31043772/37886717-f1650dec-308a-11e8-8bff-606a9dfb46d3.png">

Finally it asks for you to allow agora.gg to access certain data from your Epic Games account.
<img width="1440" alt="screen shot 2018-03-25 at 11 59 20 pm" src="https://user-images.githubusercontent.com/31043772/37886774-593e23ae-308b-11e8-9736-5d34a4a201fc.png">

My only use for this would be to verify Epic Games users for my web app and access basic user data.

I am not a coder, so I am not sure if you would need some sort of private access api that must be granted by Epic Games or if this is all open source and could be coded without permission.

As you can see, it also shows up on epicgames.com on your account page for connect accounts.
<img width="1428" alt="screen shot 2018-03-26 at 12 45 38 am" src="https://user-images.githubusercontent.com/37789486/37887331-210f5c7e-308f-11e8-9c96-a5669bcdc8e7.png">

Epic Games states in their TOS that they allow for this as long as your 3rd party service does not suggest or claim to be affiliated with them.

**Comment by julian-exile** [comment]
https://developer-paragon.epicgames.com/docs
